### ISSUE TITLE
what is it?

### ISSUE THREAD

**Issue by ResQNetM** [twaik/termux-x11#2]
Please add README file to project.
i have three questions:
1) how to use it?
2) why i get black screen
3) why it conflicts with termux?
Android 7.0 lineage os
thanks

**Comment by ResQNetM** [comment]
error when i try install termux/xwayland_proxy
Package com.termux.wtermux has no signatures that match those in shared user com.termux; ignoring!

**Comment by twaik** [comment]
1. It needs xwayland to test it.
2. You did not start Xwayland and/or X11 application.
3. It does not conflict. It is an Termux addon and needs to be signed with the same key as Termux app.
