### ISSUE TITLE
Xserver (sparkle) with "unwanted effect occurs" (UEO)

### ISSUE THREAD

**Issue by RalfWerner** [twaik/termux-x11#5]
I've been suffering from an effect on my _aarch_ device for a couple of months, called _SSM_.
Now a second _UEO_ has arrived, which shows up with the sparcle + Xwayland (Xserver) of @mogryph1 on my phone but is easier to repeat than _SSM_ - occurs immediately. To understand the effect, I created a [video](https://www.dropbox.com/s/6y3qz7ejkaifqyj/UEO.mp4?dl=0).
We had discussed the topic in [issue1](https://github.com/twaik/termux-x11/issues/1#issuecomment-521518711) until Aug. 18. The [three](https://github.com/twaik/termux-x11/issues/1#issuecomment-523360958) Xserver has pros and cons. Unfortunately I could not test Sparcle because of _UEO_.

@mogryph1 I have a bad conscience that I _"misuse"_ your work for my _UEO_ problem and maybe the reason is in my hardware. 
But I promise, if it can be solved, I will create (here) a "pro & cons" report, where I include Sparkle. The test of Sparke + Xwayland + fluxbox + aterm from termux is done with:
```
export DISPLAY=:0 XDG_RUNTIME_DIR=/data/data/com.sion.sparkle/files
am start -n com.sion.sparkle/.MainActivity; Xwayland &
ps -eo pid,ppid,comm,etime; fluxbox &
aterm -geometry 40x20+0+0 -fn -*-*-bold-r-*--24-*-*-*-*-*-*-* -bg '#eeeece' -fg blue &
```
This corresponds to the current "One-Touch-Start" (OTS) with the other Xservers and allows a wide range of check options. You wrote:
> Main Activity is **dummy** and only used to start service. You can close it after service is started.

Could I `am start ...` service direct, _without_ **dummy and how?**

**Comment by mogryph1** [comment]
@RalfWerner
Blinking can be solved by updating apk and changing upload mode from 1 to 2. Probably you don't have to update apk, but few days ago I made upload mode 2 1.5 times faster.
MainActivity is no longer dummy. And I don't know how to start service from command line. Service's name is "SparkleService".

**Comment by mogryph1** [comment]
Latest version is always available here:
ftp://ftp.drivehq.com/mogryph/sparkle/

**Comment by RalfWerner** [comment]
@mogryph1 your new version has become nice (with blue eyes) and other smart symbols. Your _**"upload mode=2"**_ suggestion has resolved the _UEO_ problem, but also hoping to find an easy way to explain my _SSM_ problem, but possibly solve.

Unfortunately I missed a few functions. Probably my ignorance. I hope you can help me out. I would like to know:
- Turn on / off on-screen KB (BT works in general - not my German special keys).
- Screen resolution (expose of mobile phone rotation, etc.) are not recognized.
- mouse / finger events are differentiated (BT mouse tested) including GenericEvents (so I wished). The two alternatives of @twaik and @xeffyr can not or not correctly.

I do not know if you've been following my _SSM (stalled mode)_ "Suffering Story" from **issue1**. Mostly, the first _SSM_ occurs after 2 to 5 minutes once, but also one time after 1.5 hours, before _first SSM_ then occurs every 3 to 7 events.

With your Xserver, I've been producing "events" for 2 hours without _SSM_ - very encouraging. If you can tell me something about the first two points above, I'll keep testing and make the promised comparison report (next week).

**Comment by mogryph1** [comment]
@RalfWerner , you can use volume up key to summon keyboard and volume down key to perform right mouse click. Screen rotation currently cannot be handled because upstream version of Xwayland doesn't support it. I use full linux distributions, not termux.
Currently I work on sparkle almost every day and often bring major changes that can break everything. Not sure it's ready for final testing and comparing with anything. Thanks for feedback anyway. I think you are one of just 3-4 people who managed to run sparkle.

**Comment by RalfWerner** [comment]
@mogryph1 I have no problem with _"half finished"_ SW or errors that are accidentally "built in". I like the "on-screen KB" solution! A 2nd Vol-up to hide would be smarter than "End" -key, especially since this is already occupied with another function. The MB3 with Vol-down in "finger" mode is almost intuitive.
The screen resolution (should also send an expose for KB-on / off) is very important for the mobile phone. The best [solution](https://github.com/termux/termux-app/issues/1203#issuecomment-519505089) I've found so far in the [APK](https://gitter.im/termux/dev?at=5d4726cd26e27324461700b6) from @xeffyr and best _termux-integration_.

**Comment by RalfWerner** [comment]
@mogryph1 has suggested `upload_mode=2` as the solution of "UEO" (This source is displayed with EDIT SETTINGS.LUA and can be changed) and I found this to be the "SSM" solution for Twaik's and Leonid's X-servers as well following actions take place before their APK's.
- After Phone reboot, start the Sparkle-X-server and close it again
- start one of their X-servers. They are only alternative and not usable at the same time but with OTS (One-Touch-Start).

If this is done, I did not notice any "SSM" anymore (in 2 hours events). Sparkle can also be started as an additional 3rd Xserver and used simultaneously with the other two. The start and also the change is a bit tedious but possible.
DISPLAY is for wtermux / X11 with ":0" with Xvnc with ":1" occupied and with sparkle I use ":2" thereby "Xwayland" can be started twice. Unfortunately, then "SSM" occurs again.

@mogryph1 Can you tell me the value (currently 2 for me) in more detail, how he influences the behavior and **what values ​​are helpful?**
Your `start service ...` proposal (above) ends with the message:
`Error: Requires permission not issued from uid 10108` **- on your device too?**
- to start: the "script" portion (4 lines above with :0 -> :2) after START (shot1)
- swipe to the sparkle notification tab on SHOW to swipe down / up (shot2) and
- the X server (shot3) will appear. If the phone is held protrait does not look so interesting.

![grafik](https://user-images.githubusercontent.com/45426380/64130066-3221c680-cdc0-11e9-8f73-88471f34d3d3.png)
**Do you know an easier way?**

**Comment by mogryph1** [comment]
@RalfWerner , `am startservice` works for me if I execute it as root. Also I could change MainActivity to make it start service and close itself quietly if called with some extra data. Like
`am start -n com.sion.sparkle/.MainActivity --el "startservice" "1"`
But I see no reason to do so... Sparkle can't be used with termux anyway (on newer devices).

Em, fine. Let's stop making **twaik** angry by discussing **sparkle** in his repository. We are competitors after all, not one friendly team.

p.s.: I've changed vol_up key to toggle keyboard as you suggested.

p.p.s: There is almost no chance that sparkle's upload_mode could affect other apps.
